baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Game Patterns'
theme = "hugo-book"

[caches]
  [caches.images]
    dir = ':cacheDir/images'


[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'
  
    # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables portable links and link checks in markdown pages.
  # Portable links meant to work with text editors and let you write markdown without {{< relref >}} shortcode
  # Theme will print warning if page referenced in markdown does not exists.
  BookPortableLinks = 'warning'