baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Game Patterns'
theme = "hugo-book"

[caches]
  [caches.images]
    dir = ':cacheDir/images'


[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'